### ISSUE TITLE
Suddenly broke, "Could not get content for /muk_web_branding/static/src/scss/primary_colors.custom.muk_web_branding._assets_primary_variables.scss"

### ISSUE THREAD

**Issue by dszego** [muk-it/muk_website#5]
I uninstalled a module called "Shortcut Icon", next thing I know the entire system breaks, and I get this error:

Could not get content for /muk_web_branding/static/src/scss/primary_colors.custom.muk_web_branding._assets_primary_variables.scss

The file doesn't even exist, nor in your GitHub repository.

Since the whole web site is now plaintext without CSS, I can't click on anything to uninstall Muk_Website_Branding or repair anything.

What goes in this file, so at least I can recreate it and hopefully have my system back?

**Comment by keshrath** [comment]
This attachment (/muk_web_branding/static/src/scss/primary_colors.custom.muk_web_branding._assets_primary_variables.scss) was created when you customized the colors. Somehow you managed to delete it. The content of the attachment is the same as in the file (/muk_web_branding/static/src/scss/primary_colors.scss) only with your customizations.

You can use the Odoo shell to interact with the system, even if the gui is broken.

I close the ticket, because it doesn't describe a reproducible bug, furthermore please create issues in the right project. A problem with the module web_branding should be created in muk_web.
